/*
 * generated by Xtext
 */
package org.nader.sennet.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SNDslUiModule extends org.nader.sennet.xtext.ui.AbstractSNDslUiModule {
	public SNDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
