<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="sennet" nsURI="http://www.sennet.xtext" nsPrefix="sn">
  <eClassifiers xsi:type="ecore:EClass" name="WSNapp" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="number_of_nodes" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="network" eType="#//Network"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="jobs" upperBound="-1" eType="#//Job"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Network" eSuperTypes="#//Identifiable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//enums/NetType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="interNodeComm" eType="#//enums/InterNodeComm"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="routingProtocol" eType="#//enums/RoutingProtocol"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1"
        eType="#//Node" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="clusters" upperBound="-1"
        eType="#//Cluster" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Node" eSuperTypes="#//Identifiable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="position" eType="#//enums/Position"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="role" eType="#//enums/NodeRole"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Cluster" eSuperTypes="#//Identifiable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="head" eType="#//Node"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" unique="false" upperBound="-1"
        eType="#//Node"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Job" eSuperTypes="#//Identifiable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//enums/JobType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="assignedElementId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defineTimer" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="data" eType="#//Data" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defineEvent" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Data">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="general_activity" eType="#//enums/GeneralActivity"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aggregation" eType="#//enums/Aggregation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resources" upperBound="-1"
        eType="#//Resource" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fusion" eType="#//enums/Fusion"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Resource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ioPort" eType="#//enums/PortType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sensorType" eType="#//enums/SensorType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="messageText" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true" eSuperTypes="#//Identifiable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Identifiable" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eSubpackages name="enums" nsURI="http://www.sennet.xtext/enums" nsPrefix="sne">
    <eClassifiers xsi:type="ecore:EEnum" name="SensorType">
      <eLiterals name="accelerometer" literal="accelerometer"/>
      <eLiterals name="light" value="1" literal="light"/>
      <eLiterals name="location" value="2" literal="location"/>
      <eLiterals name="microphone" value="3" literal="microphone"/>
      <eLiterals name="temperature" value="4" literal="temperature"/>
      <eLiterals name="pressure" value="5" literal="pressure"/>
      <eLiterals name="humidity" value="6" literal="humidity"/>
      <eLiterals name="chemical" value="7" literal="chemical"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="PortType">
      <eLiterals name="serial" literal="serial"/>
      <eLiterals name="usb" value="1" literal="usb"/>
      <eLiterals name="transmitter" value="2" literal="transmitter"/>
      <eLiterals name="receiver" value="3" literal="receiver"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="Fusion">
      <eLiterals name="classification" literal="classification"/>
      <eLiterals name="event_detection" value="1" literal="event_detection"/>
      <eLiterals name="tracking" value="2" literal="tracking"/>
      <eLiterals name="decision_making" value="3" literal="decision_making"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="Aggregation">
      <eLiterals name="filtering" literal="filtering"/>
      <eLiterals name="compression" value="1" literal="compression"/>
      <eLiterals name="max" value="2" literal="max"/>
      <eLiterals name="min" value="3" literal="min"/>
      <eLiterals name="avg" value="4" literal="ávg"/>
      <eLiterals name="count" value="5" literal="count"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="GeneralActivity">
      <eLiterals name="data_forward" literal="data_forward"/>
      <eLiterals name="store_data" value="1" literal="stor_data"/>
      <eLiterals name="message_sent" value="2" literal="message_sent"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="JobType">
      <eLiterals name="continuous" literal="Continuous"/>
      <eLiterals name="EventDriven" value="1" literal="EventDriven"/>
      <eLiterals name="periodic" value="2" literal="Periodic"/>
      <eLiterals name="RequestReply" value="3" literal="RequestReply"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="NodeRole">
      <eLiterals name="sensor_node" literal="sensor_node"/>
      <eLiterals name="cluster_head" value="1" literal="cluster_head"/>
      <eLiterals name="sink" value="2" literal="sink"/>
      <eLiterals name="computation_node" value="3" literal="computation_node"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="Position">
      <eLiterals name="mobile" literal="mobile"/>
      <eLiterals name="static" value="1" literal="static"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="RoutingProtocol">
      <eLiterals name="leach" literal="leach"/>
      <eLiterals name="lqrp" value="1" literal="lqrp"/>
      <eLiterals name="spin" value="2" literal="spin"/>
      <eLiterals name="aodv" value="3" literal="aodv"/>
      <eLiterals name="dodv" value="4" literal="dodv"/>
      <eLiterals name="dsr" value="5" literal="dsr"/>
      <eLiterals name="dsdv" value="6" literal="dsdv"/>
      <eLiterals name="gsr" value="7" literal="gsr"/>
      <eLiterals name="heed" value="8" literal="heed"/>
      <eLiterals name="gaf" value="9" literal="gaf"/>
      <eLiterals name="gear" value="10" literal="gear"/>
      <eLiterals name="tbf" value="11" literal="tbf"/>
      <eLiterals name="ead" value="12" literal="ead"/>
      <eLiterals name="pegasis" value="13" literal="pegasis"/>
      <eLiterals name="teen" value="14" literal="teen"/>
      <eLiterals name="speed" value="15" literal="speed"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="InterNodeComm">
      <eLiterals name="BT" literal="BT"/>
      <eLiterals name="Zigbee" value="1" literal="Zigbee"/>
      <eLiterals name="WLan" value="2" literal="WLan"/>
      <eLiterals name="RF" value="3" literal="RF"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="NetType">
      <eLiterals name="flat_net" literal="flat_net"/>
      <eLiterals name="cluster_net" value="1" literal="cluster_net"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
