/*
 * generated by Xtext
 */
package org.nader.sennet.xtext;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DslRuntimeModule extends org.nader.sennet.xtext.AbstractDslRuntimeModule {

}
