/*
* generated by Xtext
*/
package org.nader.sennet.xtext;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class SNDslStandaloneSetup extends SNDslStandaloneSetupGenerated{

	public static void doSetup() {
		new SNDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

