/*
* generated by Xtext
*/
package org.nader.sennet.xtext;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class SNDslUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.nader.sennet.xtext.ui.internal.SNDslActivator.getInstance().getInjector("org.nader.sennet.xtext.SNDsl");
	}
	
}
