/**
 */
package org.nader.sennet.job.jobtrigger.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

import org.nader.sennet.job.jobtrigger.util.JobtriggerAdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class JobtriggerItemProviderAdapterFactory extends JobtriggerAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public JobtriggerItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.nader.sennet.job.jobtrigger.ReceiveMessageTrigger} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ReceiveMessageTriggerItemProvider receiveMessageTriggerItemProvider;

	/**
	 * This creates an adapter for a {@link org.nader.sennet.job.jobtrigger.ReceiveMessageTrigger}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createReceiveMessageTriggerAdapter() {
		if (receiveMessageTriggerItemProvider == null) {
			receiveMessageTriggerItemProvider = new ReceiveMessageTriggerItemProvider(this);
		}

		return receiveMessageTriggerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.nader.sennet.job.jobtrigger.RecieveSerialMsgTrigger} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RecieveSerialMsgTriggerItemProvider recieveSerialMsgTriggerItemProvider;

	/**
	 * This creates an adapter for a {@link org.nader.sennet.job.jobtrigger.RecieveSerialMsgTrigger}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRecieveSerialMsgTriggerAdapter() {
		if (recieveSerialMsgTriggerItemProvider == null) {
			recieveSerialMsgTriggerItemProvider = new RecieveSerialMsgTriggerItemProvider(this);
		}

		return recieveSerialMsgTriggerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.nader.sennet.job.jobtrigger.StartJobTrigger} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StartJobTriggerItemProvider startJobTriggerItemProvider;

	/**
	 * This creates an adapter for a {@link org.nader.sennet.job.jobtrigger.StartJobTrigger}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStartJobTriggerAdapter() {
		if (startJobTriggerItemProvider == null) {
			startJobTriggerItemProvider = new StartJobTriggerItemProvider(this);
		}

		return startJobTriggerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.nader.sennet.job.jobtrigger.StopJobTrigger} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StopJobTriggerItemProvider stopJobTriggerItemProvider;

	/**
	 * This creates an adapter for a {@link org.nader.sennet.job.jobtrigger.StopJobTrigger}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStopJobTriggerAdapter() {
		if (stopJobTriggerItemProvider == null) {
			stopJobTriggerItemProvider = new StopJobTriggerItemProvider(this);
		}

		return stopJobTriggerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.nader.sennet.job.jobtrigger.PushButtomTrigger} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PushButtomTriggerItemProvider pushButtomTriggerItemProvider;

	/**
	 * This creates an adapter for a {@link org.nader.sennet.job.jobtrigger.PushButtomTrigger}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPushButtomTriggerAdapter() {
		if (pushButtomTriggerItemProvider == null) {
			pushButtomTriggerItemProvider = new PushButtomTriggerItemProvider(this);
		}

		return pushButtomTriggerItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (receiveMessageTriggerItemProvider != null) receiveMessageTriggerItemProvider.dispose();
		if (recieveSerialMsgTriggerItemProvider != null) recieveSerialMsgTriggerItemProvider.dispose();
		if (startJobTriggerItemProvider != null) startJobTriggerItemProvider.dispose();
		if (stopJobTriggerItemProvider != null) stopJobTriggerItemProvider.dispose();
		if (pushButtomTriggerItemProvider != null) pushButtomTriggerItemProvider.dispose();
	}

}
