/*
 * generated by Xtext
 */
package org.nader.sennet.xtext.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.nader.sennet.xtext.ui.internal.SNDslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SNDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return SNDslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return SNDslActivator.getInstance().getInjector(SNDslActivator.ORG_NADER_SENNET_XTEXT_SNDSL);
	}
	
}
