/*
* generated by Xtext
*/
package org.nader.sennet.xtext.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.nader.sennet.xtext.services.DslGrammarAccess;

public class DslParser extends AbstractContentAssistParser {
	
	@Inject
	private DslGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.nader.sennet.xtext.ui.contentassist.antlr.internal.InternalDslParser createParser() {
		org.nader.sennet.xtext.ui.contentassist.antlr.internal.InternalDslParser result = new org.nader.sennet.xtext.ui.contentassist.antlr.internal.InternalDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getAbstractJobAccess().getAlternatives(), "rule__AbstractJob__Alternatives");
					put(grammarAccess.getAbstractNodeAccess().getAlternatives(), "rule__AbstractNode__Alternatives");
					put(grammarAccess.getAbstractNetworkAccess().getAlternatives(), "rule__AbstractNetwork__Alternatives");
					put(grammarAccess.getAbstractStartEndingJobTriggerAccess().getAlternatives(), "rule__AbstractStartEndingJobTrigger__Alternatives");
					put(grammarAccess.getAbstratActionAccess().getAlternatives(), "rule__AbstratAction__Alternatives");
					put(grammarAccess.getAbstractSensorAccess().getAlternatives(), "rule__AbstractSensor__Alternatives");
					put(grammarAccess.getAbstractFlatNodeAccess().getAlternatives(), "rule__AbstractFlatNode__Alternatives");
					put(grammarAccess.getAbstractClusterNodeAccess().getAlternatives(), "rule__AbstractClusterNode__Alternatives");
					put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
					put(grammarAccess.getPositionAccess().getAlternatives(), "rule__Position__Alternatives");
					put(grammarAccess.getInterNodeCommAccess().getAlternatives(), "rule__InterNodeComm__Alternatives");
					put(grammarAccess.getRoutingProtocolAccess().getAlternatives(), "rule__RoutingProtocol__Alternatives");
					put(grammarAccess.getLogicalSymbolAccess().getAlternatives(), "rule__LogicalSymbol__Alternatives");
					put(grammarAccess.getLedsAccess().getAlternatives(), "rule__Leds__Alternatives");
					put(grammarAccess.getLedStatusAccess().getAlternatives(), "rule__LedStatus__Alternatives");
					put(grammarAccess.getAggregationAccess().getAlternatives(), "rule__Aggregation__Alternatives");
					put(grammarAccess.getFusionAccess().getAlternatives(), "rule__Fusion__Alternatives");
					put(grammarAccess.getSeNetAppAccess().getGroup(), "rule__SeNetApp__Group__0");
					put(grammarAccess.getSeNetAppAccess().getGroup_4(), "rule__SeNetApp__Group_4__0");
					put(grammarAccess.getSeNetAppAccess().getGroup_5(), "rule__SeNetApp__Group_5__0");
					put(grammarAccess.getSeNetAppAccess().getGroup_5_3(), "rule__SeNetApp__Group_5_3__0");
					put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
					put(grammarAccess.getSenseForwardJobAccess().getGroup(), "rule__SenseForwardJob__Group__0");
					put(grammarAccess.getSenseForwardJobAccess().getGroup_3(), "rule__SenseForwardJob__Group_3__0");
					put(grammarAccess.getSenseForwardJobAccess().getGroup_4(), "rule__SenseForwardJob__Group_4__0");
					put(grammarAccess.getSenseForwardJobAccess().getGroup_5(), "rule__SenseForwardJob__Group_5__0");
					put(grammarAccess.getSenseForwardJobAccess().getGroup_6(), "rule__SenseForwardJob__Group_6__0");
					put(grammarAccess.getSenseForwardJobAccess().getGroup_7(), "rule__SenseForwardJob__Group_7__0");
					put(grammarAccess.getSenseForwardJobAccess().getGroup_7_3(), "rule__SenseForwardJob__Group_7_3__0");
					put(grammarAccess.getSenseForwardJobAccess().getGroup_8(), "rule__SenseForwardJob__Group_8__0");
					put(grammarAccess.getSenseForwardJobAccess().getGroup_8_3(), "rule__SenseForwardJob__Group_8_3__0");
					put(grammarAccess.getAggregationJobAccess().getGroup(), "rule__AggregationJob__Group__0");
					put(grammarAccess.getAggregationJobAccess().getGroup_3(), "rule__AggregationJob__Group_3__0");
					put(grammarAccess.getAggregationJobAccess().getGroup_4(), "rule__AggregationJob__Group_4__0");
					put(grammarAccess.getAggregationJobAccess().getGroup_5(), "rule__AggregationJob__Group_5__0");
					put(grammarAccess.getAggregationJobAccess().getGroup_6(), "rule__AggregationJob__Group_6__0");
					put(grammarAccess.getAggregationJobAccess().getGroup_7(), "rule__AggregationJob__Group_7__0");
					put(grammarAccess.getAggregationJobAccess().getGroup_7_3(), "rule__AggregationJob__Group_7_3__0");
					put(grammarAccess.getAggregationJobAccess().getGroup_8(), "rule__AggregationJob__Group_8__0");
					put(grammarAccess.getAggregationJobAccess().getGroup_8_3(), "rule__AggregationJob__Group_8_3__0");
					put(grammarAccess.getFusionJobAccess().getGroup(), "rule__FusionJob__Group__0");
					put(grammarAccess.getFusionJobAccess().getGroup_3(), "rule__FusionJob__Group_3__0");
					put(grammarAccess.getFusionJobAccess().getGroup_4(), "rule__FusionJob__Group_4__0");
					put(grammarAccess.getFusionJobAccess().getGroup_5(), "rule__FusionJob__Group_5__0");
					put(grammarAccess.getFusionJobAccess().getGroup_6(), "rule__FusionJob__Group_6__0");
					put(grammarAccess.getFusionJobAccess().getGroup_7(), "rule__FusionJob__Group_7__0");
					put(grammarAccess.getFusionJobAccess().getGroup_7_3(), "rule__FusionJob__Group_7_3__0");
					put(grammarAccess.getFusionJobAccess().getGroup_8(), "rule__FusionJob__Group_8__0");
					put(grammarAccess.getFusionJobAccess().getGroup_8_3(), "rule__FusionJob__Group_8_3__0");
					put(grammarAccess.getSenseNowJobAccess().getGroup(), "rule__SenseNowJob__Group__0");
					put(grammarAccess.getSenseNowJobAccess().getGroup_3(), "rule__SenseNowJob__Group_3__0");
					put(grammarAccess.getSenseNowJobAccess().getGroup_4(), "rule__SenseNowJob__Group_4__0");
					put(grammarAccess.getSenseNowJobAccess().getGroup_5(), "rule__SenseNowJob__Group_5__0");
					put(grammarAccess.getSenseNowJobAccess().getGroup_6(), "rule__SenseNowJob__Group_6__0");
					put(grammarAccess.getSenseNowJobAccess().getGroup_6_3(), "rule__SenseNowJob__Group_6_3__0");
					put(grammarAccess.getSenseNowJobAccess().getGroup_7(), "rule__SenseNowJob__Group_7__0");
					put(grammarAccess.getSenseNowJobAccess().getGroup_7_3(), "rule__SenseNowJob__Group_7_3__0");
					put(grammarAccess.getSinkJobAccess().getGroup(), "rule__SinkJob__Group__0");
					put(grammarAccess.getSinkJobAccess().getGroup_3(), "rule__SinkJob__Group_3__0");
					put(grammarAccess.getSinkJobAccess().getGroup_4(), "rule__SinkJob__Group_4__0");
					put(grammarAccess.getSinkJobAccess().getGroup_5(), "rule__SinkJob__Group_5__0");
					put(grammarAccess.getSinkJobAccess().getGroup_6(), "rule__SinkJob__Group_6__0");
					put(grammarAccess.getSinkJobAccess().getGroup_6_3(), "rule__SinkJob__Group_6_3__0");
					put(grammarAccess.getSinkJobAccess().getGroup_7(), "rule__SinkJob__Group_7__0");
					put(grammarAccess.getSinkJobAccess().getGroup_7_3(), "rule__SinkJob__Group_7_3__0");
					put(grammarAccess.getRegularSenseJobAccess().getGroup(), "rule__RegularSenseJob__Group__0");
					put(grammarAccess.getRegularSenseJobAccess().getGroup_3(), "rule__RegularSenseJob__Group_3__0");
					put(grammarAccess.getRegularSenseJobAccess().getGroup_4(), "rule__RegularSenseJob__Group_4__0");
					put(grammarAccess.getRegularSenseJobAccess().getGroup_5(), "rule__RegularSenseJob__Group_5__0");
					put(grammarAccess.getRegularSenseJobAccess().getGroup_6(), "rule__RegularSenseJob__Group_6__0");
					put(grammarAccess.getRegularSenseJobAccess().getGroup_7(), "rule__RegularSenseJob__Group_7__0");
					put(grammarAccess.getRegularSenseJobAccess().getGroup_7_3(), "rule__RegularSenseJob__Group_7_3__0");
					put(grammarAccess.getRegularSenseJobAccess().getGroup_8(), "rule__RegularSenseJob__Group_8__0");
					put(grammarAccess.getRegularSenseJobAccess().getGroup_8_3(), "rule__RegularSenseJob__Group_8_3__0");
					put(grammarAccess.getSensorNodeAccess().getGroup(), "rule__SensorNode__Group__0");
					put(grammarAccess.getSensorNodeAccess().getGroup_3(), "rule__SensorNode__Group_3__0");
					put(grammarAccess.getSensorNodeAccess().getGroup_4(), "rule__SensorNode__Group_4__0");
					put(grammarAccess.getSensorNodeAccess().getGroup_5(), "rule__SensorNode__Group_5__0");
					put(grammarAccess.getSensorNodeAccess().getGroup_5_3(), "rule__SensorNode__Group_5_3__0");
					put(grammarAccess.getClusterHeadNodeAccess().getGroup(), "rule__ClusterHeadNode__Group__0");
					put(grammarAccess.getClusterHeadNodeAccess().getGroup_3(), "rule__ClusterHeadNode__Group_3__0");
					put(grammarAccess.getClusterHeadNodeAccess().getGroup_4(), "rule__ClusterHeadNode__Group_4__0");
					put(grammarAccess.getClusterHeadNodeAccess().getGroup_5(), "rule__ClusterHeadNode__Group_5__0");
					put(grammarAccess.getClusterHeadNodeAccess().getGroup_5_3(), "rule__ClusterHeadNode__Group_5_3__0");
					put(grammarAccess.getSinkNodeAccess().getGroup(), "rule__SinkNode__Group__0");
					put(grammarAccess.getSinkNodeAccess().getGroup_3(), "rule__SinkNode__Group_3__0");
					put(grammarAccess.getSinkNodeAccess().getGroup_4(), "rule__SinkNode__Group_4__0");
					put(grammarAccess.getSinkNodeAccess().getGroup_5(), "rule__SinkNode__Group_5__0");
					put(grammarAccess.getSinkNodeAccess().getGroup_5_3(), "rule__SinkNode__Group_5_3__0");
					put(grammarAccess.getComputationNodeAccess().getGroup(), "rule__ComputationNode__Group__0");
					put(grammarAccess.getComputationNodeAccess().getGroup_3(), "rule__ComputationNode__Group_3__0");
					put(grammarAccess.getComputationNodeAccess().getGroup_4(), "rule__ComputationNode__Group_4__0");
					put(grammarAccess.getComputationNodeAccess().getGroup_5(), "rule__ComputationNode__Group_5__0");
					put(grammarAccess.getComputationNodeAccess().getGroup_5_3(), "rule__ComputationNode__Group_5_3__0");
					put(grammarAccess.getAccelerometerSensorAccess().getGroup(), "rule__AccelerometerSensor__Group__0");
					put(grammarAccess.getLightSensorAccess().getGroup(), "rule__LightSensor__Group__0");
					put(grammarAccess.getLocationSensorAccess().getGroup(), "rule__LocationSensor__Group__0");
					put(grammarAccess.getMicrophoneSensorAccess().getGroup(), "rule__MicrophoneSensor__Group__0");
					put(grammarAccess.getTemperatureSensorAccess().getGroup(), "rule__TemperatureSensor__Group__0");
					put(grammarAccess.getPressureSensorAccess().getGroup(), "rule__PressureSensor__Group__0");
					put(grammarAccess.getHumiditySensorAccess().getGroup(), "rule__HumiditySensor__Group__0");
					put(grammarAccess.getVoltageSensorAccess().getGroup(), "rule__VoltageSensor__Group__0");
					put(grammarAccess.getFlatNetworkAccess().getGroup(), "rule__FlatNetwork__Group__0");
					put(grammarAccess.getFlatNetworkAccess().getGroup_2(), "rule__FlatNetwork__Group_2__0");
					put(grammarAccess.getFlatNetworkAccess().getGroup_3(), "rule__FlatNetwork__Group_3__0");
					put(grammarAccess.getFlatNetworkAccess().getGroup_4(), "rule__FlatNetwork__Group_4__0");
					put(grammarAccess.getFlatNetworkAccess().getGroup_5(), "rule__FlatNetwork__Group_5__0");
					put(grammarAccess.getFlatNetworkAccess().getGroup_6(), "rule__FlatNetwork__Group_6__0");
					put(grammarAccess.getFlatNetworkAccess().getGroup_6_3(), "rule__FlatNetwork__Group_6_3__0");
					put(grammarAccess.getFlatNetworkAccess().getGroup_9(), "rule__FlatNetwork__Group_9__0");
					put(grammarAccess.getFlatNetworkAccess().getGroup_9_3(), "rule__FlatNetwork__Group_9_3__0");
					put(grammarAccess.getClusteredNetworkAccess().getGroup(), "rule__ClusteredNetwork__Group__0");
					put(grammarAccess.getClusteredNetworkAccess().getGroup_2(), "rule__ClusteredNetwork__Group_2__0");
					put(grammarAccess.getClusteredNetworkAccess().getGroup_3(), "rule__ClusteredNetwork__Group_3__0");
					put(grammarAccess.getClusteredNetworkAccess().getGroup_4(), "rule__ClusteredNetwork__Group_4__0");
					put(grammarAccess.getClusteredNetworkAccess().getGroup_5(), "rule__ClusteredNetwork__Group_5__0");
					put(grammarAccess.getClusteredNetworkAccess().getGroup_6(), "rule__ClusteredNetwork__Group_6__0");
					put(grammarAccess.getClusteredNetworkAccess().getGroup_6_3(), "rule__ClusteredNetwork__Group_6_3__0");
					put(grammarAccess.getClusteredNetworkAccess().getGroup_9(), "rule__ClusteredNetwork__Group_9__0");
					put(grammarAccess.getClusteredNetworkAccess().getGroup_9_3(), "rule__ClusteredNetwork__Group_9_3__0");
					put(grammarAccess.getClusterAccess().getGroup(), "rule__Cluster__Group__0");
					put(grammarAccess.getClusterAccess().getGroup_3(), "rule__Cluster__Group_3__0");
					put(grammarAccess.getClusterAccess().getGroup_4(), "rule__Cluster__Group_4__0");
					put(grammarAccess.getClusterAccess().getGroup_4_3(), "rule__Cluster__Group_4_3__0");
					put(grammarAccess.getClusterAccess().getGroup_5(), "rule__Cluster__Group_5__0");
					put(grammarAccess.getClusterAccess().getGroup_5_3(), "rule__Cluster__Group_5_3__0");
					put(grammarAccess.getReceiveMessageTriggerAccess().getGroup(), "rule__ReceiveMessageTrigger__Group__0");
					put(grammarAccess.getRecieveSerialMsgTriggerAccess().getGroup(), "rule__RecieveSerialMsgTrigger__Group__0");
					put(grammarAccess.getStartJobTrigger_ImplAccess().getGroup(), "rule__StartJobTrigger_Impl__Group__0");
					put(grammarAccess.getStopJobTrigger_ImplAccess().getGroup(), "rule__StopJobTrigger_Impl__Group__0");
					put(grammarAccess.getPushButtomTriggerAccess().getGroup(), "rule__PushButtomTrigger__Group__0");
					put(grammarAccess.getConditionalActionAccess().getGroup(), "rule__ConditionalAction__Group__0");
					put(grammarAccess.getConditionalActionAccess().getGroup_3(), "rule__ConditionalAction__Group_3__0");
					put(grammarAccess.getConditionalActionAccess().getGroup_4(), "rule__ConditionalAction__Group_4__0");
					put(grammarAccess.getConditionalActionAccess().getGroup_5(), "rule__ConditionalAction__Group_5__0");
					put(grammarAccess.getConditionalActionAccess().getGroup_6(), "rule__ConditionalAction__Group_6__0");
					put(grammarAccess.getReadNodeMemoryActionAccess().getGroup(), "rule__ReadNodeMemoryAction__Group__0");
					put(grammarAccess.getWriteNodeMemoryActionAccess().getGroup(), "rule__WriteNodeMemoryAction__Group__0");
					put(grammarAccess.getSendMessageActionAccess().getGroup(), "rule__SendMessageAction__Group__0");
					put(grammarAccess.getSendMessageActionAccess().getGroup_2(), "rule__SendMessageAction__Group_2__0");
					put(grammarAccess.getBlinkActionAccess().getGroup(), "rule__BlinkAction__Group__0");
					put(grammarAccess.getBlinkActionAccess().getGroup_2(), "rule__BlinkAction__Group_2__0");
					put(grammarAccess.getBlinkActionAccess().getGroup_3(), "rule__BlinkAction__Group_3__0");
					put(grammarAccess.getSendSerialPortMsgActionAccess().getGroup(), "rule__SendSerialPortMsgAction__Group__0");
					put(grammarAccess.getELongAccess().getGroup(), "rule__ELong__Group__0");
					put(grammarAccess.getSeNetAppAccess().getNameAssignment_2(), "rule__SeNetApp__NameAssignment_2");
					put(grammarAccess.getSeNetAppAccess().getIdAssignment_4_1(), "rule__SeNetApp__IdAssignment_4_1");
					put(grammarAccess.getSeNetAppAccess().getJobsAssignment_5_2(), "rule__SeNetApp__JobsAssignment_5_2");
					put(grammarAccess.getSeNetAppAccess().getJobsAssignment_5_3_1(), "rule__SeNetApp__JobsAssignment_5_3_1");
					put(grammarAccess.getSenseForwardJobAccess().getIdAssignment_3_1(), "rule__SenseForwardJob__IdAssignment_3_1");
					put(grammarAccess.getSenseForwardJobAccess().getSensingThresholdAssignment_4_1(), "rule__SenseForwardJob__SensingThresholdAssignment_4_1");
					put(grammarAccess.getSenseForwardJobAccess().getJobTargetNodeAssignment_5_1(), "rule__SenseForwardJob__JobTargetNodeAssignment_5_1");
					put(grammarAccess.getSenseForwardJobAccess().getJobTargetNetworkAssignment_6_1(), "rule__SenseForwardJob__JobTargetNetworkAssignment_6_1");
					put(grammarAccess.getSenseForwardJobAccess().getStartEndTriggerAssignment_7_2(), "rule__SenseForwardJob__StartEndTriggerAssignment_7_2");
					put(grammarAccess.getSenseForwardJobAccess().getStartEndTriggerAssignment_7_3_1(), "rule__SenseForwardJob__StartEndTriggerAssignment_7_3_1");
					put(grammarAccess.getSenseForwardJobAccess().getJobactionAssignment_8_2(), "rule__SenseForwardJob__JobactionAssignment_8_2");
					put(grammarAccess.getSenseForwardJobAccess().getJobactionAssignment_8_3_1(), "rule__SenseForwardJob__JobactionAssignment_8_3_1");
					put(grammarAccess.getAggregationJobAccess().getIdAssignment_3_1(), "rule__AggregationJob__IdAssignment_3_1");
					put(grammarAccess.getAggregationJobAccess().getAggregationAssignment_4_1(), "rule__AggregationJob__AggregationAssignment_4_1");
					put(grammarAccess.getAggregationJobAccess().getJobTargetNodeAssignment_5_1(), "rule__AggregationJob__JobTargetNodeAssignment_5_1");
					put(grammarAccess.getAggregationJobAccess().getJobTargetNetworkAssignment_6_1(), "rule__AggregationJob__JobTargetNetworkAssignment_6_1");
					put(grammarAccess.getAggregationJobAccess().getStartEndTriggerAssignment_7_2(), "rule__AggregationJob__StartEndTriggerAssignment_7_2");
					put(grammarAccess.getAggregationJobAccess().getStartEndTriggerAssignment_7_3_1(), "rule__AggregationJob__StartEndTriggerAssignment_7_3_1");
					put(grammarAccess.getAggregationJobAccess().getJobactionAssignment_8_2(), "rule__AggregationJob__JobactionAssignment_8_2");
					put(grammarAccess.getAggregationJobAccess().getJobactionAssignment_8_3_1(), "rule__AggregationJob__JobactionAssignment_8_3_1");
					put(grammarAccess.getFusionJobAccess().getIdAssignment_3_1(), "rule__FusionJob__IdAssignment_3_1");
					put(grammarAccess.getFusionJobAccess().getFusionAssignment_4_1(), "rule__FusionJob__FusionAssignment_4_1");
					put(grammarAccess.getFusionJobAccess().getJobTargetNodeAssignment_5_1(), "rule__FusionJob__JobTargetNodeAssignment_5_1");
					put(grammarAccess.getFusionJobAccess().getJobTargetNetworkAssignment_6_1(), "rule__FusionJob__JobTargetNetworkAssignment_6_1");
					put(grammarAccess.getFusionJobAccess().getStartEndTriggerAssignment_7_2(), "rule__FusionJob__StartEndTriggerAssignment_7_2");
					put(grammarAccess.getFusionJobAccess().getStartEndTriggerAssignment_7_3_1(), "rule__FusionJob__StartEndTriggerAssignment_7_3_1");
					put(grammarAccess.getFusionJobAccess().getJobactionAssignment_8_2(), "rule__FusionJob__JobactionAssignment_8_2");
					put(grammarAccess.getFusionJobAccess().getJobactionAssignment_8_3_1(), "rule__FusionJob__JobactionAssignment_8_3_1");
					put(grammarAccess.getSenseNowJobAccess().getIdAssignment_3_1(), "rule__SenseNowJob__IdAssignment_3_1");
					put(grammarAccess.getSenseNowJobAccess().getJobTargetNodeAssignment_4_1(), "rule__SenseNowJob__JobTargetNodeAssignment_4_1");
					put(grammarAccess.getSenseNowJobAccess().getJobTargetNetworkAssignment_5_1(), "rule__SenseNowJob__JobTargetNetworkAssignment_5_1");
					put(grammarAccess.getSenseNowJobAccess().getStartEndTriggerAssignment_6_2(), "rule__SenseNowJob__StartEndTriggerAssignment_6_2");
					put(grammarAccess.getSenseNowJobAccess().getStartEndTriggerAssignment_6_3_1(), "rule__SenseNowJob__StartEndTriggerAssignment_6_3_1");
					put(grammarAccess.getSenseNowJobAccess().getJobactionAssignment_7_2(), "rule__SenseNowJob__JobactionAssignment_7_2");
					put(grammarAccess.getSenseNowJobAccess().getJobactionAssignment_7_3_1(), "rule__SenseNowJob__JobactionAssignment_7_3_1");
					put(grammarAccess.getSinkJobAccess().getIdAssignment_3_1(), "rule__SinkJob__IdAssignment_3_1");
					put(grammarAccess.getSinkJobAccess().getJobTargetNodeAssignment_4_1(), "rule__SinkJob__JobTargetNodeAssignment_4_1");
					put(grammarAccess.getSinkJobAccess().getJobTargetNetworkAssignment_5_1(), "rule__SinkJob__JobTargetNetworkAssignment_5_1");
					put(grammarAccess.getSinkJobAccess().getStartEndTriggerAssignment_6_2(), "rule__SinkJob__StartEndTriggerAssignment_6_2");
					put(grammarAccess.getSinkJobAccess().getStartEndTriggerAssignment_6_3_1(), "rule__SinkJob__StartEndTriggerAssignment_6_3_1");
					put(grammarAccess.getSinkJobAccess().getJobactionAssignment_7_2(), "rule__SinkJob__JobactionAssignment_7_2");
					put(grammarAccess.getSinkJobAccess().getJobactionAssignment_7_3_1(), "rule__SinkJob__JobactionAssignment_7_3_1");
					put(grammarAccess.getRegularSenseJobAccess().getIdAssignment_3_1(), "rule__RegularSenseJob__IdAssignment_3_1");
					put(grammarAccess.getRegularSenseJobAccess().getSensingThresholdAssignment_4_1(), "rule__RegularSenseJob__SensingThresholdAssignment_4_1");
					put(grammarAccess.getRegularSenseJobAccess().getJobTargetNodeAssignment_5_1(), "rule__RegularSenseJob__JobTargetNodeAssignment_5_1");
					put(grammarAccess.getRegularSenseJobAccess().getJobTargetNetworkAssignment_6_1(), "rule__RegularSenseJob__JobTargetNetworkAssignment_6_1");
					put(grammarAccess.getRegularSenseJobAccess().getStartEndTriggerAssignment_7_2(), "rule__RegularSenseJob__StartEndTriggerAssignment_7_2");
					put(grammarAccess.getRegularSenseJobAccess().getStartEndTriggerAssignment_7_3_1(), "rule__RegularSenseJob__StartEndTriggerAssignment_7_3_1");
					put(grammarAccess.getRegularSenseJobAccess().getJobactionAssignment_8_2(), "rule__RegularSenseJob__JobactionAssignment_8_2");
					put(grammarAccess.getRegularSenseJobAccess().getJobactionAssignment_8_3_1(), "rule__RegularSenseJob__JobactionAssignment_8_3_1");
					put(grammarAccess.getSensorNodeAccess().getIdAssignment_3_1(), "rule__SensorNode__IdAssignment_3_1");
					put(grammarAccess.getSensorNodeAccess().getPositionAssignment_4_1(), "rule__SensorNode__PositionAssignment_4_1");
					put(grammarAccess.getSensorNodeAccess().getNodeResourcesAssignment_5_2(), "rule__SensorNode__NodeResourcesAssignment_5_2");
					put(grammarAccess.getSensorNodeAccess().getNodeResourcesAssignment_5_3_1(), "rule__SensorNode__NodeResourcesAssignment_5_3_1");
					put(grammarAccess.getClusterHeadNodeAccess().getIdAssignment_3_1(), "rule__ClusterHeadNode__IdAssignment_3_1");
					put(grammarAccess.getClusterHeadNodeAccess().getPositionAssignment_4_1(), "rule__ClusterHeadNode__PositionAssignment_4_1");
					put(grammarAccess.getClusterHeadNodeAccess().getNodeResourcesAssignment_5_2(), "rule__ClusterHeadNode__NodeResourcesAssignment_5_2");
					put(grammarAccess.getClusterHeadNodeAccess().getNodeResourcesAssignment_5_3_1(), "rule__ClusterHeadNode__NodeResourcesAssignment_5_3_1");
					put(grammarAccess.getSinkNodeAccess().getIdAssignment_3_1(), "rule__SinkNode__IdAssignment_3_1");
					put(grammarAccess.getSinkNodeAccess().getPositionAssignment_4_1(), "rule__SinkNode__PositionAssignment_4_1");
					put(grammarAccess.getSinkNodeAccess().getNodeResourcesAssignment_5_2(), "rule__SinkNode__NodeResourcesAssignment_5_2");
					put(grammarAccess.getSinkNodeAccess().getNodeResourcesAssignment_5_3_1(), "rule__SinkNode__NodeResourcesAssignment_5_3_1");
					put(grammarAccess.getComputationNodeAccess().getIdAssignment_3_1(), "rule__ComputationNode__IdAssignment_3_1");
					put(grammarAccess.getComputationNodeAccess().getPositionAssignment_4_1(), "rule__ComputationNode__PositionAssignment_4_1");
					put(grammarAccess.getComputationNodeAccess().getNodeResourcesAssignment_5_2(), "rule__ComputationNode__NodeResourcesAssignment_5_2");
					put(grammarAccess.getComputationNodeAccess().getNodeResourcesAssignment_5_3_1(), "rule__ComputationNode__NodeResourcesAssignment_5_3_1");
					put(grammarAccess.getFlatNetworkAccess().getIdAssignment_2_1(), "rule__FlatNetwork__IdAssignment_2_1");
					put(grammarAccess.getFlatNetworkAccess().getNbOfNodesAssignment_3_1(), "rule__FlatNetwork__NbOfNodesAssignment_3_1");
					put(grammarAccess.getFlatNetworkAccess().getInterNodeCommAssignment_4_1(), "rule__FlatNetwork__InterNodeCommAssignment_4_1");
					put(grammarAccess.getFlatNetworkAccess().getRoutingProtocolAssignment_5_1(), "rule__FlatNetwork__RoutingProtocolAssignment_5_1");
					put(grammarAccess.getFlatNetworkAccess().getResourcesAssignment_6_2(), "rule__FlatNetwork__ResourcesAssignment_6_2");
					put(grammarAccess.getFlatNetworkAccess().getResourcesAssignment_6_3_1(), "rule__FlatNetwork__ResourcesAssignment_6_3_1");
					put(grammarAccess.getFlatNetworkAccess().getSinkAssignment_8(), "rule__FlatNetwork__SinkAssignment_8");
					put(grammarAccess.getFlatNetworkAccess().getNodesAssignment_9_2(), "rule__FlatNetwork__NodesAssignment_9_2");
					put(grammarAccess.getFlatNetworkAccess().getNodesAssignment_9_3_1(), "rule__FlatNetwork__NodesAssignment_9_3_1");
					put(grammarAccess.getClusteredNetworkAccess().getIdAssignment_2_1(), "rule__ClusteredNetwork__IdAssignment_2_1");
					put(grammarAccess.getClusteredNetworkAccess().getNbOfNodesAssignment_3_1(), "rule__ClusteredNetwork__NbOfNodesAssignment_3_1");
					put(grammarAccess.getClusteredNetworkAccess().getInterNodeCommAssignment_4_1(), "rule__ClusteredNetwork__InterNodeCommAssignment_4_1");
					put(grammarAccess.getClusteredNetworkAccess().getRoutingProtocolAssignment_5_1(), "rule__ClusteredNetwork__RoutingProtocolAssignment_5_1");
					put(grammarAccess.getClusteredNetworkAccess().getResourcesAssignment_6_2(), "rule__ClusteredNetwork__ResourcesAssignment_6_2");
					put(grammarAccess.getClusteredNetworkAccess().getResourcesAssignment_6_3_1(), "rule__ClusteredNetwork__ResourcesAssignment_6_3_1");
					put(grammarAccess.getClusteredNetworkAccess().getSinkAssignment_8(), "rule__ClusteredNetwork__SinkAssignment_8");
					put(grammarAccess.getClusteredNetworkAccess().getClustersAssignment_9_2(), "rule__ClusteredNetwork__ClustersAssignment_9_2");
					put(grammarAccess.getClusteredNetworkAccess().getClustersAssignment_9_3_1(), "rule__ClusteredNetwork__ClustersAssignment_9_3_1");
					put(grammarAccess.getClusterAccess().getIdAssignment_3_1(), "rule__Cluster__IdAssignment_3_1");
					put(grammarAccess.getClusterAccess().getResourcesAssignment_4_2(), "rule__Cluster__ResourcesAssignment_4_2");
					put(grammarAccess.getClusterAccess().getResourcesAssignment_4_3_1(), "rule__Cluster__ResourcesAssignment_4_3_1");
					put(grammarAccess.getClusterAccess().getNodesAssignment_5_2(), "rule__Cluster__NodesAssignment_5_2");
					put(grammarAccess.getClusterAccess().getNodesAssignment_5_3_1(), "rule__Cluster__NodesAssignment_5_3_1");
					put(grammarAccess.getConditionalActionAccess().getSensorTermAssignment_3_1(), "rule__ConditionalAction__SensorTermAssignment_3_1");
					put(grammarAccess.getConditionalActionAccess().getLogicalSymbolAssignment_4_1(), "rule__ConditionalAction__LogicalSymbolAssignment_4_1");
					put(grammarAccess.getConditionalActionAccess().getValueAssignment_5_1(), "rule__ConditionalAction__ValueAssignment_5_1");
					put(grammarAccess.getConditionalActionAccess().getUnitAssignment_6_1(), "rule__ConditionalAction__UnitAssignment_6_1");
					put(grammarAccess.getReadNodeMemoryActionAccess().getConditionAssignment_3(), "rule__ReadNodeMemoryAction__ConditionAssignment_3");
					put(grammarAccess.getWriteNodeMemoryActionAccess().getConditionAssignment_3(), "rule__WriteNodeMemoryAction__ConditionAssignment_3");
					put(grammarAccess.getSendMessageActionAccess().getSendMessageToAssignment_2_1(), "rule__SendMessageAction__SendMessageToAssignment_2_1");
					put(grammarAccess.getSendMessageActionAccess().getConditionAssignment_4(), "rule__SendMessageAction__ConditionAssignment_4");
					put(grammarAccess.getBlinkActionAccess().getLedAssignment_2_1(), "rule__BlinkAction__LedAssignment_2_1");
					put(grammarAccess.getBlinkActionAccess().getStatusAssignment_3_1(), "rule__BlinkAction__StatusAssignment_3_1");
					put(grammarAccess.getBlinkActionAccess().getConditionAssignment_5(), "rule__BlinkAction__ConditionAssignment_5");
					put(grammarAccess.getSendSerialPortMsgActionAccess().getConditionAssignment_3(), "rule__SendSerialPortMsgAction__ConditionAssignment_3");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.nader.sennet.xtext.ui.contentassist.antlr.internal.InternalDslParser typedParser = (org.nader.sennet.xtext.ui.contentassist.antlr.internal.InternalDslParser) parser;
			typedParser.entryRuleSeNetApp();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public DslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(DslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
