/*
* generated by Xtext
*/
package org.nader.sennet.xtext.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.nader.sennet.xtext.services.SNDslGrammarAccess;

public class SNDslParser extends AbstractContentAssistParser {
	
	@Inject
	private SNDslGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.nader.sennet.xtext.ui.contentassist.antlr.internal.InternalSNDslParser createParser() {
		org.nader.sennet.xtext.ui.contentassist.antlr.internal.InternalSNDslParser result = new org.nader.sennet.xtext.ui.contentassist.antlr.internal.InternalSNDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getAbstractNetworkAccess().getAlternatives(), "rule__AbstractNetwork__Alternatives");
					put(grammarAccess.getAbstractJobAccess().getAlternatives(), "rule__AbstractJob__Alternatives");
					put(grammarAccess.getAbstractPortAccess().getAlternatives(), "rule__AbstractPort__Alternatives");
					put(grammarAccess.getAbstractSensorAccess().getAlternatives(), "rule__AbstractSensor__Alternatives");
					put(grammarAccess.getAbstractFlatNodeAccess().getAlternatives(), "rule__AbstractFlatNode__Alternatives");
					put(grammarAccess.getAbstractClusterNodeAccess().getAlternatives(), "rule__AbstractClusterNode__Alternatives");
					put(grammarAccess.getAbstractJobActionAccess().getAlternatives(), "rule__AbstractJobAction__Alternatives");
					put(grammarAccess.getAbstractNodeAccess().getAlternatives(), "rule__AbstractNode__Alternatives");
					put(grammarAccess.getOutPortAccess().getAlternatives(), "rule__OutPort__Alternatives");
					put(grammarAccess.getInPortAccess().getAlternatives(), "rule__InPort__Alternatives");
					put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
					put(grammarAccess.getInterNodeCommAccess().getAlternatives(), "rule__InterNodeComm__Alternatives");
					put(grammarAccess.getRoutingProtocolAccess().getAlternatives(), "rule__RoutingProtocol__Alternatives");
					put(grammarAccess.getPositionAccess().getAlternatives(), "rule__Position__Alternatives");
					put(grammarAccess.getAggregationAccess().getAlternatives(), "rule__Aggregation__Alternatives");
					put(grammarAccess.getFusionAccess().getAlternatives(), "rule__Fusion__Alternatives");
					put(grammarAccess.getJobScheduleAccess().getAlternatives(), "rule__JobSchedule__Alternatives");
					put(grammarAccess.getLogicalSymbolAccess().getAlternatives(), "rule__LogicalSymbol__Alternatives");
					put(grammarAccess.getWSNappAccess().getGroup(), "rule__WSNapp__Group__0");
					put(grammarAccess.getWSNappAccess().getGroup_4(), "rule__WSNapp__Group_4__0");
					put(grammarAccess.getWSNappAccess().getGroup_5(), "rule__WSNapp__Group_5__0");
					put(grammarAccess.getWSNappAccess().getGroup_6(), "rule__WSNapp__Group_6__0");
					put(grammarAccess.getWSNappAccess().getGroup_6_3(), "rule__WSNapp__Group_6_3__0");
					put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
					put(grammarAccess.getSinkNodeAccess().getGroup(), "rule__SinkNode__Group__0");
					put(grammarAccess.getSinkNodeAccess().getGroup_3(), "rule__SinkNode__Group_3__0");
					put(grammarAccess.getSinkNodeAccess().getGroup_4(), "rule__SinkNode__Group_4__0");
					put(grammarAccess.getSinkNodeAccess().getGroup_5(), "rule__SinkNode__Group_5__0");
					put(grammarAccess.getSinkNodeAccess().getGroup_5_3(), "rule__SinkNode__Group_5_3__0");
					put(grammarAccess.getSinkNodeAccess().getGroup_6(), "rule__SinkNode__Group_6__0");
					put(grammarAccess.getSinkNodeAccess().getGroup_6_3(), "rule__SinkNode__Group_6_3__0");
					put(grammarAccess.getFlatNetworkAccess().getGroup(), "rule__FlatNetwork__Group__0");
					put(grammarAccess.getFlatNetworkAccess().getGroup_3(), "rule__FlatNetwork__Group_3__0");
					put(grammarAccess.getFlatNetworkAccess().getGroup_4(), "rule__FlatNetwork__Group_4__0");
					put(grammarAccess.getFlatNetworkAccess().getGroup_5(), "rule__FlatNetwork__Group_5__0");
					put(grammarAccess.getFlatNetworkAccess().getGroup_6(), "rule__FlatNetwork__Group_6__0");
					put(grammarAccess.getFlatNetworkAccess().getGroup_7(), "rule__FlatNetwork__Group_7__0");
					put(grammarAccess.getFlatNetworkAccess().getGroup_8(), "rule__FlatNetwork__Group_8__0");
					put(grammarAccess.getFlatNetworkAccess().getGroup_8_3(), "rule__FlatNetwork__Group_8_3__0");
					put(grammarAccess.getFlatNetworkAccess().getGroup_9(), "rule__FlatNetwork__Group_9__0");
					put(grammarAccess.getFlatNetworkAccess().getGroup_9_3(), "rule__FlatNetwork__Group_9_3__0");
					put(grammarAccess.getFlatNetworkAccess().getGroup_10(), "rule__FlatNetwork__Group_10__0");
					put(grammarAccess.getFlatNetworkAccess().getGroup_10_3(), "rule__FlatNetwork__Group_10_3__0");
					put(grammarAccess.getClusteredNetworkAccess().getGroup(), "rule__ClusteredNetwork__Group__0");
					put(grammarAccess.getClusteredNetworkAccess().getGroup_3(), "rule__ClusteredNetwork__Group_3__0");
					put(grammarAccess.getClusteredNetworkAccess().getGroup_4(), "rule__ClusteredNetwork__Group_4__0");
					put(grammarAccess.getClusteredNetworkAccess().getGroup_5(), "rule__ClusteredNetwork__Group_5__0");
					put(grammarAccess.getClusteredNetworkAccess().getGroup_6(), "rule__ClusteredNetwork__Group_6__0");
					put(grammarAccess.getClusteredNetworkAccess().getGroup_7(), "rule__ClusteredNetwork__Group_7__0");
					put(grammarAccess.getClusteredNetworkAccess().getGroup_8(), "rule__ClusteredNetwork__Group_8__0");
					put(grammarAccess.getClusteredNetworkAccess().getGroup_8_3(), "rule__ClusteredNetwork__Group_8_3__0");
					put(grammarAccess.getClusteredNetworkAccess().getGroup_9(), "rule__ClusteredNetwork__Group_9__0");
					put(grammarAccess.getClusteredNetworkAccess().getGroup_9_3(), "rule__ClusteredNetwork__Group_9_3__0");
					put(grammarAccess.getClusteredNetworkAccess().getGroup_10(), "rule__ClusteredNetwork__Group_10__0");
					put(grammarAccess.getClusteredNetworkAccess().getGroup_10_3(), "rule__ClusteredNetwork__Group_10_3__0");
					put(grammarAccess.getAccelerometerSensorAccess().getGroup(), "rule__AccelerometerSensor__Group__0");
					put(grammarAccess.getLightSensorAccess().getGroup(), "rule__LightSensor__Group__0");
					put(grammarAccess.getLocationSensorAccess().getGroup(), "rule__LocationSensor__Group__0");
					put(grammarAccess.getMicrophoneSensorAccess().getGroup(), "rule__MicrophoneSensor__Group__0");
					put(grammarAccess.getTemperatureSensorAccess().getGroup(), "rule__TemperatureSensor__Group__0");
					put(grammarAccess.getPressureSensorAccess().getGroup(), "rule__PressureSensor__Group__0");
					put(grammarAccess.getHumiditySensorAccess().getGroup(), "rule__HumiditySensor__Group__0");
					put(grammarAccess.getChemicalSensorAccess().getGroup(), "rule__ChemicalSensor__Group__0");
					put(grammarAccess.getUsbPortAccess().getGroup(), "rule__UsbPort__Group__0");
					put(grammarAccess.getSerialPortAccess().getGroup(), "rule__SerialPort__Group__0");
					put(grammarAccess.getOutPort_ImplAccess().getGroup(), "rule__OutPort_Impl__Group__0");
					put(grammarAccess.getInPort_ImplAccess().getGroup(), "rule__InPort_Impl__Group__0");
					put(grammarAccess.getTransmitterAccess().getGroup(), "rule__Transmitter__Group__0");
					put(grammarAccess.getRecieverAccess().getGroup(), "rule__Reciever__Group__0");
					put(grammarAccess.getSensorNodeAccess().getGroup(), "rule__SensorNode__Group__0");
					put(grammarAccess.getSensorNodeAccess().getGroup_3(), "rule__SensorNode__Group_3__0");
					put(grammarAccess.getSensorNodeAccess().getGroup_4(), "rule__SensorNode__Group_4__0");
					put(grammarAccess.getSensorNodeAccess().getGroup_5(), "rule__SensorNode__Group_5__0");
					put(grammarAccess.getSensorNodeAccess().getGroup_5_3(), "rule__SensorNode__Group_5_3__0");
					put(grammarAccess.getSensorNodeAccess().getGroup_6(), "rule__SensorNode__Group_6__0");
					put(grammarAccess.getSensorNodeAccess().getGroup_6_3(), "rule__SensorNode__Group_6_3__0");
					put(grammarAccess.getComputationNodeAccess().getGroup(), "rule__ComputationNode__Group__0");
					put(grammarAccess.getComputationNodeAccess().getGroup_3(), "rule__ComputationNode__Group_3__0");
					put(grammarAccess.getComputationNodeAccess().getGroup_4(), "rule__ComputationNode__Group_4__0");
					put(grammarAccess.getComputationNodeAccess().getGroup_5(), "rule__ComputationNode__Group_5__0");
					put(grammarAccess.getComputationNodeAccess().getGroup_5_3(), "rule__ComputationNode__Group_5_3__0");
					put(grammarAccess.getComputationNodeAccess().getGroup_6(), "rule__ComputationNode__Group_6__0");
					put(grammarAccess.getComputationNodeAccess().getGroup_6_3(), "rule__ComputationNode__Group_6_3__0");
					put(grammarAccess.getClusterAccess().getGroup(), "rule__Cluster__Group__0");
					put(grammarAccess.getClusterAccess().getGroup_3(), "rule__Cluster__Group_3__0");
					put(grammarAccess.getClusterAccess().getGroup_4(), "rule__Cluster__Group_4__0");
					put(grammarAccess.getClusterAccess().getGroup_4_3(), "rule__Cluster__Group_4_3__0");
					put(grammarAccess.getClusterAccess().getGroup_5(), "rule__Cluster__Group_5__0");
					put(grammarAccess.getClusterAccess().getGroup_6(), "rule__Cluster__Group_6__0");
					put(grammarAccess.getClusterAccess().getGroup_6_3(), "rule__Cluster__Group_6_3__0");
					put(grammarAccess.getClusterHeadNodeAccess().getGroup(), "rule__ClusterHeadNode__Group__0");
					put(grammarAccess.getClusterHeadNodeAccess().getGroup_3(), "rule__ClusterHeadNode__Group_3__0");
					put(grammarAccess.getClusterHeadNodeAccess().getGroup_4(), "rule__ClusterHeadNode__Group_4__0");
					put(grammarAccess.getClusterHeadNodeAccess().getGroup_5(), "rule__ClusterHeadNode__Group_5__0");
					put(grammarAccess.getClusterHeadNodeAccess().getGroup_5_3(), "rule__ClusterHeadNode__Group_5_3__0");
					put(grammarAccess.getClusterHeadNodeAccess().getGroup_6(), "rule__ClusterHeadNode__Group_6__0");
					put(grammarAccess.getClusterHeadNodeAccess().getGroup_6_3(), "rule__ClusterHeadNode__Group_6_3__0");
					put(grammarAccess.getContinuousJobAccess().getGroup(), "rule__ContinuousJob__Group__0");
					put(grammarAccess.getContinuousJobAccess().getGroup_3(), "rule__ContinuousJob__Group_3__0");
					put(grammarAccess.getContinuousJobAccess().getGroup_4(), "rule__ContinuousJob__Group_4__0");
					put(grammarAccess.getEventDrivenJobAccess().getGroup(), "rule__EventDrivenJob__Group__0");
					put(grammarAccess.getEventDrivenJobAccess().getGroup_3(), "rule__EventDrivenJob__Group_3__0");
					put(grammarAccess.getEventDrivenJobAccess().getGroup_4(), "rule__EventDrivenJob__Group_4__0");
					put(grammarAccess.getEventDrivenJobAccess().getGroup_5(), "rule__EventDrivenJob__Group_5__0");
					put(grammarAccess.getPeriodicJobAccess().getGroup(), "rule__PeriodicJob__Group__0");
					put(grammarAccess.getPeriodicJobAccess().getGroup_3(), "rule__PeriodicJob__Group_3__0");
					put(grammarAccess.getPeriodicJobAccess().getGroup_4(), "rule__PeriodicJob__Group_4__0");
					put(grammarAccess.getPeriodicJobAccess().getGroup_5(), "rule__PeriodicJob__Group_5__0");
					put(grammarAccess.getRequestReplayJobAccess().getGroup(), "rule__RequestReplayJob__Group__0");
					put(grammarAccess.getRequestReplayJobAccess().getGroup_3(), "rule__RequestReplayJob__Group_3__0");
					put(grammarAccess.getRequestReplayJobAccess().getGroup_4(), "rule__RequestReplayJob__Group_4__0");
					put(grammarAccess.getSenseForwardActionAccess().getGroup(), "rule__SenseForwardAction__Group__0");
					put(grammarAccess.getSenseForwardActionAccess().getGroup_3(), "rule__SenseForwardAction__Group_3__0");
					put(grammarAccess.getSenseForwardActionAccess().getGroup_4(), "rule__SenseForwardAction__Group_4__0");
					put(grammarAccess.getAggregationActionAccess().getGroup(), "rule__AggregationAction__Group__0");
					put(grammarAccess.getAggregationActionAccess().getGroup_3(), "rule__AggregationAction__Group_3__0");
					put(grammarAccess.getAggregationActionAccess().getGroup_4(), "rule__AggregationAction__Group_4__0");
					put(grammarAccess.getAggregationActionAccess().getGroup_5(), "rule__AggregationAction__Group_5__0");
					put(grammarAccess.getFusionActionAccess().getGroup(), "rule__FusionAction__Group__0");
					put(grammarAccess.getFusionActionAccess().getGroup_3(), "rule__FusionAction__Group_3__0");
					put(grammarAccess.getFusionActionAccess().getGroup_4(), "rule__FusionAction__Group_4__0");
					put(grammarAccess.getFusionActionAccess().getGroup_5(), "rule__FusionAction__Group_5__0");
					put(grammarAccess.getFusionActionAccess().getGroup_6(), "rule__FusionAction__Group_6__0");
					put(grammarAccess.getReadNodeMemoryActionAccess().getGroup(), "rule__ReadNodeMemoryAction__Group__0");
					put(grammarAccess.getReadNodeMemoryActionAccess().getGroup_3(), "rule__ReadNodeMemoryAction__Group_3__0");
					put(grammarAccess.getReadNodeMemoryActionAccess().getGroup_4(), "rule__ReadNodeMemoryAction__Group_4__0");
					put(grammarAccess.getWriteNodeMemoryActionAccess().getGroup(), "rule__WriteNodeMemoryAction__Group__0");
					put(grammarAccess.getWriteNodeMemoryActionAccess().getGroup_3(), "rule__WriteNodeMemoryAction__Group_3__0");
					put(grammarAccess.getWriteNodeMemoryActionAccess().getGroup_4(), "rule__WriteNodeMemoryAction__Group_4__0");
					put(grammarAccess.getSendMessageActionAccess().getGroup(), "rule__SendMessageAction__Group__0");
					put(grammarAccess.getSendMessageActionAccess().getGroup_3(), "rule__SendMessageAction__Group_3__0");
					put(grammarAccess.getSendMessageActionAccess().getGroup_4(), "rule__SendMessageAction__Group_4__0");
					put(grammarAccess.getSendMessageActionAccess().getGroup_5(), "rule__SendMessageAction__Group_5__0");
					put(grammarAccess.getSendMessageActionAccess().getGroup_6(), "rule__SendMessageAction__Group_6__0");
					put(grammarAccess.getReceiveMessageActionAccess().getGroup(), "rule__ReceiveMessageAction__Group__0");
					put(grammarAccess.getReceiveMessageActionAccess().getGroup_3(), "rule__ReceiveMessageAction__Group_3__0");
					put(grammarAccess.getReceiveMessageActionAccess().getGroup_4(), "rule__ReceiveMessageAction__Group_4__0");
					put(grammarAccess.getReceiveMessageActionAccess().getGroup_5(), "rule__ReceiveMessageAction__Group_5__0");
					put(grammarAccess.getLogicalConditionAccess().getGroup(), "rule__LogicalCondition__Group__0");
					put(grammarAccess.getLogicalConditionAccess().getGroup_3(), "rule__LogicalCondition__Group_3__0");
					put(grammarAccess.getLogicalConditionAccess().getGroup_4(), "rule__LogicalCondition__Group_4__0");
					put(grammarAccess.getLogicalConditionAccess().getGroup_5(), "rule__LogicalCondition__Group_5__0");
					put(grammarAccess.getLogicalConditionAccess().getGroup_6(), "rule__LogicalCondition__Group_6__0");
					put(grammarAccess.getLogicalConditionAccess().getGroup_7(), "rule__LogicalCondition__Group_7__0");
					put(grammarAccess.getELongAccess().getGroup(), "rule__ELong__Group__0");
					put(grammarAccess.getWSNappAccess().getNameAssignment_2(), "rule__WSNapp__NameAssignment_2");
					put(grammarAccess.getWSNappAccess().getIdAssignment_4_1(), "rule__WSNapp__IdAssignment_4_1");
					put(grammarAccess.getWSNappAccess().getNetworkAssignment_5_1(), "rule__WSNapp__NetworkAssignment_5_1");
					put(grammarAccess.getWSNappAccess().getJobsAssignment_6_2(), "rule__WSNapp__JobsAssignment_6_2");
					put(grammarAccess.getWSNappAccess().getJobsAssignment_6_3_1(), "rule__WSNapp__JobsAssignment_6_3_1");
					put(grammarAccess.getSinkNodeAccess().getIdAssignment_3_1(), "rule__SinkNode__IdAssignment_3_1");
					put(grammarAccess.getSinkNodeAccess().getPositionAssignment_4_1(), "rule__SinkNode__PositionAssignment_4_1");
					put(grammarAccess.getSinkNodeAccess().getPortsAssignment_5_2(), "rule__SinkNode__PortsAssignment_5_2");
					put(grammarAccess.getSinkNodeAccess().getPortsAssignment_5_3_1(), "rule__SinkNode__PortsAssignment_5_3_1");
					put(grammarAccess.getSinkNodeAccess().getSensorsAssignment_6_2(), "rule__SinkNode__SensorsAssignment_6_2");
					put(grammarAccess.getSinkNodeAccess().getSensorsAssignment_6_3_1(), "rule__SinkNode__SensorsAssignment_6_3_1");
					put(grammarAccess.getFlatNetworkAccess().getIdAssignment_3_1(), "rule__FlatNetwork__IdAssignment_3_1");
					put(grammarAccess.getFlatNetworkAccess().getNbOfNodesAssignment_4_1(), "rule__FlatNetwork__NbOfNodesAssignment_4_1");
					put(grammarAccess.getFlatNetworkAccess().getInterNodeCommAssignment_5_1(), "rule__FlatNetwork__InterNodeCommAssignment_5_1");
					put(grammarAccess.getFlatNetworkAccess().getRoutingProtocolAssignment_6_1(), "rule__FlatNetwork__RoutingProtocolAssignment_6_1");
					put(grammarAccess.getFlatNetworkAccess().getSinkAssignment_7_1(), "rule__FlatNetwork__SinkAssignment_7_1");
					put(grammarAccess.getFlatNetworkAccess().getSensorsAssignment_8_2(), "rule__FlatNetwork__SensorsAssignment_8_2");
					put(grammarAccess.getFlatNetworkAccess().getSensorsAssignment_8_3_1(), "rule__FlatNetwork__SensorsAssignment_8_3_1");
					put(grammarAccess.getFlatNetworkAccess().getPortsAssignment_9_2(), "rule__FlatNetwork__PortsAssignment_9_2");
					put(grammarAccess.getFlatNetworkAccess().getPortsAssignment_9_3_1(), "rule__FlatNetwork__PortsAssignment_9_3_1");
					put(grammarAccess.getFlatNetworkAccess().getNodesAssignment_10_2(), "rule__FlatNetwork__NodesAssignment_10_2");
					put(grammarAccess.getFlatNetworkAccess().getNodesAssignment_10_3_1(), "rule__FlatNetwork__NodesAssignment_10_3_1");
					put(grammarAccess.getClusteredNetworkAccess().getIdAssignment_3_1(), "rule__ClusteredNetwork__IdAssignment_3_1");
					put(grammarAccess.getClusteredNetworkAccess().getNbOfNodesAssignment_4_1(), "rule__ClusteredNetwork__NbOfNodesAssignment_4_1");
					put(grammarAccess.getClusteredNetworkAccess().getInterNodeCommAssignment_5_1(), "rule__ClusteredNetwork__InterNodeCommAssignment_5_1");
					put(grammarAccess.getClusteredNetworkAccess().getRoutingProtocolAssignment_6_1(), "rule__ClusteredNetwork__RoutingProtocolAssignment_6_1");
					put(grammarAccess.getClusteredNetworkAccess().getSinkAssignment_7_1(), "rule__ClusteredNetwork__SinkAssignment_7_1");
					put(grammarAccess.getClusteredNetworkAccess().getSensorsAssignment_8_2(), "rule__ClusteredNetwork__SensorsAssignment_8_2");
					put(grammarAccess.getClusteredNetworkAccess().getSensorsAssignment_8_3_1(), "rule__ClusteredNetwork__SensorsAssignment_8_3_1");
					put(grammarAccess.getClusteredNetworkAccess().getPortsAssignment_9_2(), "rule__ClusteredNetwork__PortsAssignment_9_2");
					put(grammarAccess.getClusteredNetworkAccess().getPortsAssignment_9_3_1(), "rule__ClusteredNetwork__PortsAssignment_9_3_1");
					put(grammarAccess.getClusteredNetworkAccess().getClustersAssignment_10_2(), "rule__ClusteredNetwork__ClustersAssignment_10_2");
					put(grammarAccess.getClusteredNetworkAccess().getClustersAssignment_10_3_1(), "rule__ClusteredNetwork__ClustersAssignment_10_3_1");
					put(grammarAccess.getSensorNodeAccess().getIdAssignment_3_1(), "rule__SensorNode__IdAssignment_3_1");
					put(grammarAccess.getSensorNodeAccess().getPositionAssignment_4_1(), "rule__SensorNode__PositionAssignment_4_1");
					put(grammarAccess.getSensorNodeAccess().getPortsAssignment_5_2(), "rule__SensorNode__PortsAssignment_5_2");
					put(grammarAccess.getSensorNodeAccess().getPortsAssignment_5_3_1(), "rule__SensorNode__PortsAssignment_5_3_1");
					put(grammarAccess.getSensorNodeAccess().getSensorsAssignment_6_2(), "rule__SensorNode__SensorsAssignment_6_2");
					put(grammarAccess.getSensorNodeAccess().getSensorsAssignment_6_3_1(), "rule__SensorNode__SensorsAssignment_6_3_1");
					put(grammarAccess.getComputationNodeAccess().getIdAssignment_3_1(), "rule__ComputationNode__IdAssignment_3_1");
					put(grammarAccess.getComputationNodeAccess().getPositionAssignment_4_1(), "rule__ComputationNode__PositionAssignment_4_1");
					put(grammarAccess.getComputationNodeAccess().getPortsAssignment_5_2(), "rule__ComputationNode__PortsAssignment_5_2");
					put(grammarAccess.getComputationNodeAccess().getPortsAssignment_5_3_1(), "rule__ComputationNode__PortsAssignment_5_3_1");
					put(grammarAccess.getComputationNodeAccess().getSensorsAssignment_6_2(), "rule__ComputationNode__SensorsAssignment_6_2");
					put(grammarAccess.getComputationNodeAccess().getSensorsAssignment_6_3_1(), "rule__ComputationNode__SensorsAssignment_6_3_1");
					put(grammarAccess.getClusterAccess().getIdAssignment_3_1(), "rule__Cluster__IdAssignment_3_1");
					put(grammarAccess.getClusterAccess().getResourcesAssignment_4_2(), "rule__Cluster__ResourcesAssignment_4_2");
					put(grammarAccess.getClusterAccess().getResourcesAssignment_4_3_1(), "rule__Cluster__ResourcesAssignment_4_3_1");
					put(grammarAccess.getClusterAccess().getHeadAssignment_5_1(), "rule__Cluster__HeadAssignment_5_1");
					put(grammarAccess.getClusterAccess().getNodesAssignment_6_2(), "rule__Cluster__NodesAssignment_6_2");
					put(grammarAccess.getClusterAccess().getNodesAssignment_6_3_1(), "rule__Cluster__NodesAssignment_6_3_1");
					put(grammarAccess.getClusterHeadNodeAccess().getIdAssignment_3_1(), "rule__ClusterHeadNode__IdAssignment_3_1");
					put(grammarAccess.getClusterHeadNodeAccess().getPositionAssignment_4_1(), "rule__ClusterHeadNode__PositionAssignment_4_1");
					put(grammarAccess.getClusterHeadNodeAccess().getPortsAssignment_5_2(), "rule__ClusterHeadNode__PortsAssignment_5_2");
					put(grammarAccess.getClusterHeadNodeAccess().getPortsAssignment_5_3_1(), "rule__ClusterHeadNode__PortsAssignment_5_3_1");
					put(grammarAccess.getClusterHeadNodeAccess().getSensorsAssignment_6_2(), "rule__ClusterHeadNode__SensorsAssignment_6_2");
					put(grammarAccess.getClusterHeadNodeAccess().getSensorsAssignment_6_3_1(), "rule__ClusterHeadNode__SensorsAssignment_6_3_1");
					put(grammarAccess.getContinuousJobAccess().getIdAssignment_3_1(), "rule__ContinuousJob__IdAssignment_3_1");
					put(grammarAccess.getContinuousJobAccess().getActionAssignment_4_1(), "rule__ContinuousJob__ActionAssignment_4_1");
					put(grammarAccess.getEventDrivenJobAccess().getIdAssignment_3_1(), "rule__EventDrivenJob__IdAssignment_3_1");
					put(grammarAccess.getEventDrivenJobAccess().getActionAssignment_4_1(), "rule__EventDrivenJob__ActionAssignment_4_1");
					put(grammarAccess.getEventDrivenJobAccess().getEventConditionAssignment_5_1(), "rule__EventDrivenJob__EventConditionAssignment_5_1");
					put(grammarAccess.getPeriodicJobAccess().getIdAssignment_3_1(), "rule__PeriodicJob__IdAssignment_3_1");
					put(grammarAccess.getPeriodicJobAccess().getTimerAssignment_4_1(), "rule__PeriodicJob__TimerAssignment_4_1");
					put(grammarAccess.getPeriodicJobAccess().getActionAssignment_5_1(), "rule__PeriodicJob__ActionAssignment_5_1");
					put(grammarAccess.getRequestReplayJobAccess().getIdAssignment_3_1(), "rule__RequestReplayJob__IdAssignment_3_1");
					put(grammarAccess.getRequestReplayJobAccess().getActionAssignment_4_1(), "rule__RequestReplayJob__ActionAssignment_4_1");
					put(grammarAccess.getSenseForwardActionAccess().getSinkNodeAssignment_3_1(), "rule__SenseForwardAction__SinkNodeAssignment_3_1");
					put(grammarAccess.getSenseForwardActionAccess().getTargetNodeAssignment_4_1(), "rule__SenseForwardAction__TargetNodeAssignment_4_1");
					put(grammarAccess.getAggregationActionAccess().getAggregationAssignment_3_1(), "rule__AggregationAction__AggregationAssignment_3_1");
					put(grammarAccess.getAggregationActionAccess().getSinkNodeAssignment_4_1(), "rule__AggregationAction__SinkNodeAssignment_4_1");
					put(grammarAccess.getAggregationActionAccess().getTargetNodeAssignment_5_1(), "rule__AggregationAction__TargetNodeAssignment_5_1");
					put(grammarAccess.getFusionActionAccess().getFusionAssignment_3_1(), "rule__FusionAction__FusionAssignment_3_1");
					put(grammarAccess.getFusionActionAccess().getSinkNodeAssignment_4_1(), "rule__FusionAction__SinkNodeAssignment_4_1");
					put(grammarAccess.getFusionActionAccess().getCompuNodeAssignment_5_1(), "rule__FusionAction__CompuNodeAssignment_5_1");
					put(grammarAccess.getFusionActionAccess().getClusterHeadAssignment_6_1(), "rule__FusionAction__ClusterHeadAssignment_6_1");
					put(grammarAccess.getReadNodeMemoryActionAccess().getSinkNodeAssignment_3_1(), "rule__ReadNodeMemoryAction__SinkNodeAssignment_3_1");
					put(grammarAccess.getReadNodeMemoryActionAccess().getTargetNodeAssignment_4_1(), "rule__ReadNodeMemoryAction__TargetNodeAssignment_4_1");
					put(grammarAccess.getWriteNodeMemoryActionAccess().getSinkNodeAssignment_3_1(), "rule__WriteNodeMemoryAction__SinkNodeAssignment_3_1");
					put(grammarAccess.getWriteNodeMemoryActionAccess().getTargetNodeAssignment_4_1(), "rule__WriteNodeMemoryAction__TargetNodeAssignment_4_1");
					put(grammarAccess.getSendMessageActionAccess().getTextAssignment_3_1(), "rule__SendMessageAction__TextAssignment_3_1");
					put(grammarAccess.getSendMessageActionAccess().getSinkNodeAssignment_4_1(), "rule__SendMessageAction__SinkNodeAssignment_4_1");
					put(grammarAccess.getSendMessageActionAccess().getTargetNodeAssignment_5_1(), "rule__SendMessageAction__TargetNodeAssignment_5_1");
					put(grammarAccess.getSendMessageActionAccess().getOutPortAssignment_6_1(), "rule__SendMessageAction__OutPortAssignment_6_1");
					put(grammarAccess.getReceiveMessageActionAccess().getSinkNodeAssignment_3_1(), "rule__ReceiveMessageAction__SinkNodeAssignment_3_1");
					put(grammarAccess.getReceiveMessageActionAccess().getTargetNodeAssignment_4_1(), "rule__ReceiveMessageAction__TargetNodeAssignment_4_1");
					put(grammarAccess.getReceiveMessageActionAccess().getInPortAssignment_5_1(), "rule__ReceiveMessageAction__InPortAssignment_5_1");
					put(grammarAccess.getLogicalConditionAccess().getJobScheduleAssignment_3_1(), "rule__LogicalCondition__JobScheduleAssignment_3_1");
					put(grammarAccess.getLogicalConditionAccess().getSensorTermAssignment_4_1(), "rule__LogicalCondition__SensorTermAssignment_4_1");
					put(grammarAccess.getLogicalConditionAccess().getLogicalSymbolAssignment_5_1(), "rule__LogicalCondition__LogicalSymbolAssignment_5_1");
					put(grammarAccess.getLogicalConditionAccess().getValueAssignment_6_1(), "rule__LogicalCondition__ValueAssignment_6_1");
					put(grammarAccess.getLogicalConditionAccess().getUnitAssignment_7_1(), "rule__LogicalCondition__UnitAssignment_7_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.nader.sennet.xtext.ui.contentassist.antlr.internal.InternalSNDslParser typedParser = (org.nader.sennet.xtext.ui.contentassist.antlr.internal.InternalSNDslParser) parser;
			typedParser.entryRuleWSNapp();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public SNDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(SNDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
