/*
 * generated by Xtext
 */
package org.nader.sennet.xtext.ui.contentassist

import org.nader.sennet.xtext.ui.contentassist.AbstractSNDslProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class SNDslProposalProvider extends AbstractSNDslProposalProvider {
}
